model:
  name: bond_predictor
  node_dim: 128
  edge_dim: 32
  center_pos_mode: protein
  knn: 32
  cutoff_mode: knn
  encoder:
    backbone: EGNN
    num_blocks: 8
    cutoff: 20
    use_gate: True
    update_edge: True
    update_pos: False  # pos should not be updated
  diff:
    num_timesteps: 1000
    time_dim: 10
    categorical_space: discrete
    diff_pos:
      beta_schedule: advance
      scale_start: 0.9999
      scale_end: 0.0001
      width: 3
    diff_atom: 
      init_prob: tomask
      beta_schedule: advance
      scale_start: 0.9999
      scale_end: 0.0001
      width: 3

train:
  seed: 2023
  batch_size: 16
  num_workers: 0
  num_accum: 4
  pin_memory: True
  max_iters: 600000
  val_freq: 1000
  train_report_iter: 1
  pos_noise_std: 0.1
  max_grad_norm: 8.0
  use_amp: True
  optimizer:
    type: adamw
    lr: 5.e-4
    weight_decay: 1.e-8
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 10
    min_lr: 1.e-8

data:
  name: protein_ligand
  path: datas/PDBbind_v2020/PDBbind_v2020_pocket10
  split: datas/PDBbind_v2020/PDBbind_pocket10_split.pt
  transform:
    ligand_atom_mode: aromatic # [basic, aromatic, full]
    random_rot: False
    sample: False