model:
  checkpoint: checkpoints/trained.pt
  gen_mode: denovo  # denovo or ligand_ref
  ligand: None
# frag: None

bond_predictor: checkpoints/bondpred.pt

sample:
  seed: 42
  batch_size: 64
  num_mols: 100
  save_traj_prob: 0
  sample: True
  sample_method: priori
  mode: test # pocket or test
  add_edge: None
  guidance:
    - uncertainty
    - 1.e-4


data:
  name: protein_ligand
  path: datas/PDBbind_v2020/PDBbind_v2020_pocket10
  split: datas/PDBbind_v2020/PDBbind_pocket10_split.pt
  protein_root: datas/PDBbind_v2020/source
  dataset: pdbbind # [pdbbind, crossdocked]
  transform:
    ligand_atom_mode: aromatic # [basic, aromatic, full]
    random_rot: False
    sample: False